name: PHP CI Pipeline

on push:
  branches:
    - main

jobs
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run PHP
      run: php index.php
